language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t tripham93/docker-react -f Dockerfile.dev .
  
script:
  - docker run -e CI=true tripham93/docker-react npm run test